name: Course Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: pint-test-${{ github.ref }}-1
  cancel-in-progress: true

permissions:
  contents: read

env:
  cache_key: pint-test-build-cache-v1

jobs:
  env-setup:
    name: Set variables
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.set-variables.outputs.cache-key }}
    steps:
      - name: Set variables
        id: set-variables
        run: echo "::set-output name=cache-key::${{ env.cache_key }}"

  code-style:
    needs: [ env-setup ]
    uses: edu-cat/.github/.github/workflows/_code_style_pint.yml@master
    with:
      cache_key: ${{ needs.env-setup.outputs.cache-key }}
